### ISSUE TITLE
Continued compliance with the HSTS preload requirements.

### ISSUE THREAD

**Issue by bardiharborow** [tlhunter/php-wordpress-thomashunter-theme#7]
Hey! `thomashunter.name` is currently HSTS preloaded, but has not continued to remain compliant with the [preload requirements](https://hstspreload.org/). If you are able to remedy this, it would be highly appreciated. This will ensure that if Chrome begins delisting non-compliant domains that yours will not be affected. Over at [EFForg/https-everywhere](https://github.com/EFForg/https-everywhere), we can't remove rewrite rules for domains that are non-compliant because that would present a security risk if Chrome then also removes them. Your domain is one of hundreds of non-compliant domains which add unnecessary maintenance and file size to our rulesets. Any assistance you can provide is appreciated.

**Comment by tlhunter** [comment]
`www.thomashunter.name` now answers to HTTPS requests. This issue should now be rectified though I'm not sure how to notify the https-everywhere project.

**Comment by bardiharborow** [comment]
`http://www.thomashunter.name` needs to redirect to `https://www.thomashunter.name` before redirecting to `https://thomashunter.name` (a stupid technicality I know).

**Comment by tlhunter** [comment]
Change has been made, visitors now get the double redirect.

**Comment by bardiharborow** [comment]
`includeSubDomains` is missing now. It's probably too much hassle, so I'll just close this.
